[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 100_000
via_ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[profile.intense.fuzz]
  runs = 1_000

[rpc_endpoints]
sonic = '${SONIC_RPC_URL}'

[etherscan]
sonic = { key = "${ETHERSCAN_API_KEY}", url = 'https://api.sonicscan.org/api', chain = 146 }

[profile.dev]
  via_ir = false